v1=input("Write anything: ")
print ("Primitive type is", v1.__class__)
print("Is numeric?", v1.isnumeric())
print("I alpha?", v1.isalpha())
print("Is alphanumeric?", v1.isalnum())
print("Has only spaces?", v1.isspace())
#print("Is capitalized?",v1.istitle())
#print("Is in supper?", v1.isupper())
#print("Is in slower?", v1.islower())